import {
    Users,
    MessageSquare,
    Bell,
    BookOpen,
    Trophy,
    Brain,
    Lightbulb,
    MessageCircle,
    Shield,
    UserPlus as UserPen,
    Home,
    Waypoints, Tags, ChartBarStacked, TableOfContents, NotebookTabs,
} from "lucide-react"

export const getNavigationItems = (username?: string) => [
    {
        name: "Home",
        href: "/home",
        icon: Home,
        description: "Home page",
        color: "bg-red-600",
    },
    {
        name: "My Profile",
        href: `/profiles/${username ?? ""}`,
        icon: UserPen,
        description: "Manage your profile",
        color: "bg-purple-600",
    },
    {
        name: "Explore",
        href: "/feed",
        icon: Waypoints,
        description: "Discover personalized feed",
        color: "bg-emerald-600",
    },
    {
        name: "Friends",
        href: "/friends",
        icon: Users,
        description: "Manage connections",
        color: "bg-rose-500",
    },
    {
        name: "Chat",
        href: "/chat",
        icon: MessageSquare,
        description: "Chat with friends",
        color: "bg-green-600",
    },
    {
        name: "Notifications",
        href: "/notifications",
        icon: Bell,
        description: "Stay Updated",
        color: "bg-amber-500",
    },
    {
        name: "Learning",
        href: "/learning",
        icon: BookOpen,
        description: "Learn with courses and quizzes",
        color: "bg-blue-600",
    },
    {
        name: "Leaderboard",
        href: "/leaderboard",
        icon: Trophy,
        description: "Rankings & Achievements",
        color: "bg-orange-500",
    },
    {
        name: "Feedback Center",
        href: "/feedback",
        icon: MessageCircle,
        description: "Share Your Experience",
        color: "bg-violet-600",
    },
    {
        name: "AI Assistant",
        href: "/ai-coach",
        icon: Brain,
        description: "Personalized assistant",
        color: "bg-purple-600",
    },
    {
        name: "Daily Inspiration",
        href: "/daily",
        icon: Lightbulb,
        description: "Quotes & Tips",
        color: "bg-yellow-500",
    },
    {
        name: "Admin Panel",
        href: "/admin",
        icon: Shield,
        description: "System Management",
        color: "bg-slate-600",
    },
    {
        name: "Tags",
        href: "/tags",
        icon: Tags,
        description: "Tags Management",
        color: "bg-teal-600",
    },
    {
        name: "Categories",
        href: "/categories",
        icon: ChartBarStacked,
        description: "Categories Management",
        color: "bg-orange-600",
    },
    {
        name: "Content Management",
        href: "/content",
        icon: TableOfContents,
        description: "Content Management Lesson",
        color: "bg-indigo-600",
    },
    {
        name: "Lessons Management",
        href: "/lessons",
        icon: BookOpen,
        description: "Management Lessons",
        color: "bg-red-600",
    },
    {
        name: "Modules Management",
        href: "/modules",
        icon: NotebookTabs,
        description: "Modules Lessons",
        color: "bg-pink-600",
    }
]
